name: sample-react-app
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: get docker version
        run: docker --version
      - name: List current directory
        run: ls -al
  docker:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: build docker image
        run: docker build -t sample-react-app -f ./Dockerfile.dev .
